(function (g) {
  (g.SIM_SCENARIOS = g.SIM_SCENARIOS || []).push({
    id: 'ch5', n: 5, title: 'Metrics Monitoring & Alerting', subtitle: 'Метрики, дашборды и алерты',
    intro: 'Тысячи серверов каждые несколько секунд присылают числа. Нужно всё сохранить, быстро рисовать графики и вовремя будить дежурного. Нагрузка на запись постоянная и огромная, на чтение «пилой».',
    flows: [{ id: 'write', label: 'Запись метрик' }, { id: 'read', label: 'Дашборды и алерты' }],
    inputs: [
      { id: 'servers', label: 'Серверов', unit: '', min: 100, max: 100000, step: 100, value: 10000 },
      { id: 'metrics', label: 'Метрик на сервер', unit: '', min: 20, max: 500, step: 10, value: 100 },
      { id: 'interval', label: 'Интервал сбора', unit: 'с', min: 1, max: 60, step: 1, value: 10 },
      { id: 'ret', label: 'Хранить сырые данные', unit: 'дней', min: 1, max: 365, step: 1, value: 30 },
      { id: 'spike', label: 'Всплеск записи', unit: '×', min: 1, max: 5, step: 0.5, value: 3 },
      { id: 'dash', label: 'Запросы дашбордов', unit: '/с', min: 10, max: 3000, step: 10, value: 300 },
      { id: 'rules', label: 'Правил алертов', unit: '', min: 100, max: 100000, step: 100, value: 20000 },
    ],
    baseQuality: 25, qualityLabel: 'Полнота и сохранность метрик', qualityHint: 'Не теряем ли метрики при пиках и сбоях и не заваливаем ли дежурных шумом.',
    derive: (i) => { const w = (i.servers * i.metrics) / i.interval; return { w, wpeak: w * i.spike, tb: (w * 86400 * i.ret * 16) / 1e12, q: i.dash, evals: i.rules / 60 }; },
    load: (d) => ({ col: d.wpeak, kafka: d.w, store: d.wpeak, disk: d.tb * 4, query: d.q, alert: d.evals }),
    stages: [
      { id: 'col', name: 'Сбор (collectors)', icon: '📥', unit: 'точек/с', cap: 20000, lat: 10, avail: 0.995, cost: 250, flow: 'write', note: 'Список серверов задан вручную' },
      { id: 'kafka', name: 'Kafka-буфер', icon: '🧵', unit: 'точек/с', cap: 150000, lat: 4, avail: 0.999, cost: 600, flow: 'write', path: false, hidden: true },
      { id: 'store', name: 'MySQL (таблица метрик)', icon: '🗄️', unit: 'точек/с', cap: 2500, lat: 20, avail: 0.995, cost: 450, flow: 'write' },
      { id: 'disk', name: 'Хранилище (с индексами)', icon: '💾', unit: 'ТБ', cap: 4, lat: 0, avail: 0.9995, cost: 120, flow: 'write', path: false, follow: 'store', redundant: false },
      { id: 'query', name: 'Query service', icon: '📈', unit: 'req/s', cap: 120, lat: 220, avail: 0.995, cost: 300, flow: 'read', note: 'Читает сырые точки за весь период' },
      { id: 'alert', name: 'Alert manager', icon: '🔔', unit: 'проверок/с', cap: 150, lat: 60, avail: 0.995, cost: 250, flow: 'read', note: 'Наивно: каждая сработка сразу уходит в почту' },
    ],
    components: [
      { id: 'pull', group: 'collect', name: 'Pull: сборщики опрашивают сервисы', icon: '🎣', at: 'col', cx: 3, q: 10,
        apply: (s) => { s.stages.col.capMult *= 1.3; s.stages.col.note = 'Сервисы открывают /metrics, сборщики опрашивают по списку из service discovery'; },
        learn: { what: 'Collectors сами ходят к серверам за метриками (как в Prometheus). Актуальный список целей берут из service discovery (etcd/ZooKeeper).',
          why: 'Просто проверять «жив ли сервис», нет нужды в агентах и очередях на стороне приложений.',
          must: ['Нужен service discovery, чтобы знать, кого опрашивать.', 'Чтобы collectors не опрашивали одни и те же цели, цели делят consistent hashing.', 'Сложно для короткоживущих задач и сетей за NAT.'], risks: ['Нужен доступ сборщиков к сервисам по сети.'] } },
      { id: 'push', group: 'collect', name: 'Push: агенты шлют на балансировщик', icon: '📤', at: 'col', cx: 2, q: 5,
        apply: (s) => { s.stages.col.capMult *= 1.2; s.stages.col.note = 'Агент на каждой машине отправляет метрики на сборщики за LB'; },
        learn: { what: 'Агент на сервере собирает метрики и сам отправляет их на кластер сборщиков за балансировщиком.', why: 'Работает для эфемерных задач и сетей, в которые снаружи не достучаться.',
          must: ['Агент должен буферизовать и ретраить.', 'Сборщики автомасштабируются, ведь они stateless.', 'Сложнее проверять «жив ли сервис».'], risks: ['Нужно ставить и обновлять агентов на всех машинах.'] } },
      { id: 'kafka', name: 'Kafka между сбором и хранилищем', icon: '🧵', at: 'kafka', cx: 3, q: 25, cost: 0,
        apply: (s, d) => { s.stages.kafka.hidden = false; s.stages.store.load = d.w * 1.1; },
        learn: { what: 'Сборщики пишут в Kafka, а отдельные consumer-ы переливают точки в TSDB.', why: 'Буфер сглаживает всплески и переживает перезапуск или сбой базы без потери данных.',
          must: ['Хранилище видит ровный поток, а не пики.', 'Данные можно перечитать при ошибке.', 'Партиционирование по метрике/тегу.'], risks: ['Лишний компонент и дополнительная задержка.'] } },
      { id: 'tsdb', name: 'Time-series DB (TSDB)', icon: '⏱️', at: 'store', cx: 2, q: 5,
        apply: (s) => { const x = s.stages.store; x.name = 'TSDB (InfluxDB/Prometheus-like)'; x.cap = 40000; x.lat = 5; s.stages.disk.load *= 0.25; s.stages.query.cap = 400; s.stages.query.lat = 70; },
        learn: { what: 'Специализированная БД для рядов «метрика + теги → (время, значение)».', why: 'Оптимизирована под постоянную запись и агрегации по времени. В реляционной таблице индексы и построчное хранение раздувают данные.',
          must: ['Модель: имя метрики, теги (labels), точки времени.', 'Запросы почти всегда «за период с агрегацией».', 'Мало тегов с высокой кардинальностью: иначе индекс взорвётся.'], risks: ['Ограниченный SQL и миграция данных.'] } },
      { id: 'compress', name: 'Сжатие (delta-of-delta, XOR)', icon: '🗜️', at: 'disk', cx: 1, q: 0, requires: ['tsdb'],
        apply: (s) => { s.stages.disk.load *= 0.35; },
        learn: { what: 'Хранят разницы между соседними временными метками и значениями, а не сами числа.', why: 'Метрики между соседними точками почти не меняются, поэтому сжатие в разы.',
          must: ['Читать нужно с декомпрессией, это обычно быстро.'], risks: [] } },
      { id: 'downsample', name: 'Downsampling (1 мин → 1 час)', icon: '📉', at: 'disk', cx: 2, q: -8, requires: ['tsdb'],
        apply: (s) => { s.stages.disk.load *= 0.3; s.stages.query.lat *= 0.5; },
        learn: { what: 'Старые данные укрупняют: через 7 дней хранят точки раз в минуту, через 30 дней раз в час.', why: 'Для графика за год не нужна секундная точность, а хранить её дорого.',
          must: ['Нужно продумать политику хранения и что именно агрегируем (avg/max/p99).'], risks: ['Теряем детали: старые пики и аномалии сглаживаются.'] } },
      { id: 'qcache', name: 'Кэш результатов запросов', icon: '⚡', at: 'query', cx: 1, q: 0,
        apply: (s) => { s.stages.query.load *= 0.3; },
        learn: { what: 'Одинаковые запросы дашбордов (их открывают много людей) берутся из кэша.', why: 'Дашборды опрашивают одно и то же каждые несколько секунд.', must: ['Короткий TTL, чтобы график не отставал.'], risks: ['Чуть устаревшие данные.'] } },
      { id: 'alertmgr', name: 'Alert manager (группировка, дедупликация, retry)', icon: '🛎️', at: 'alert', cx: 3, q: 20,
        apply: (s) => { s.stages.alert.cap = 600; s.stages.alert.note = 'Группирует, подавляет дубли, делает retry каналов'; },
        learn: { what: 'Правила проверяются периодически; сработки объединяются, дедуплицируются и уходят в каналы (email, PagerDuty).', why: 'Без этого одна авария порождает шторм одинаковых писем, и дежурные перестают их читать.',
          must: ['Состояние алертов хранится (key-value), чтобы не слать повторы.', 'Нужны silence и приоритеты.'], risks: ['Агрессивная группировка может скрыть важное.'] } },
      { id: 'repl', name: 'Репликация хранилища', icon: '🧬', at: 'store', cx: 2, cost: 1200, q: 15,
        apply: (s) => { s.stages.store.avail = 0.99999; s.stages.store.redundant = false; s.stages.disk.load *= 2; },
        learn: { what: 'Данные TSDB пишутся минимум на две-три машины.', why: 'Падение узла не должно терять метрики и ломать дашборды.', must: ['Диски растут пропорционально числу копий.'], risks: ['Дороже и сложнее.'] } },
    ],
    rules: (s, d, st, m, warn) => {
      if (!st.active.pull && !st.active.push) warn('info', 'Способ сбора не выбран: сравни pull (Prometheus-стиль) и push (агенты).');
      if (st.active.pull && s.stages.col.replicas > 1) warn('info', 'При нескольких сборщиках цели делят consistent hashing, чтобы не опрашивать одно и то же дважды.');
      if (!st.active.tsdb) warn('info', 'Реляционная таблица раздувается индексами. Посмотри на узкие места записи и диска.');
      if (st.active.downsample) warn('info', 'Downsampling экономит диск, но старые пики сглаживаются. Выбери агрегаты (max, p99) аккуратно.');
    },
    goals: [
      { text: 'Выдерживаем 100% нагрузки', check: (m) => m.served >= 1 && m.maxU <= 0.9 },
      { text: 'Дашборд отвечает до 150 мс', check: (m) => m.lat.read <= 150 },
      { text: 'Сохранность метрик ≥ 70', check: (m) => m.quality >= 70 },
      { text: 'Сложность не выше 14 из 20', check: (m) => m.cx <= 14 },
    ],
    tryThis: ['С включённым «Автомасштабом» посмотри, во что обходится MySQL, и замени его на TSDB.', 'Добавь Kafka и сравни, как изменилась нагрузка на хранилище при пиках.', 'Поставь срок хранения 365 дней: что делать с диском (сжатие, downsampling)?', 'Подними правила алертов до 100 000.'],
  });
})(typeof window !== 'undefined' ? window : globalThis);
